# Generated by Django 4.0.10 on 2023-03-30 13:56

from django.db import migrations, models
import student_welfare_backend.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_faculty",
            field=models.BooleanField(default=False, verbose_name="User is faculty"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_no",
            field=models.CharField(
                default=911, max_length=15, verbose_name="Phone number of User"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="tenure",
            field=models.CharField(
                blank=True,
                max_length=4,
                validators=[student_welfare_backend.users.models.validate_tenure],
                verbose_name="Pass out year of the student",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[student_welfare_backend.users.models.validate_email],
                verbose_name="Email of User",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name of User"),
        ),
    ]
