# Generated by Django 4.0.10 on 2024-03-27 15:57

from django.db import migrations, models
import student_welfare_backend.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_adsw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenure',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[student_welfare_backend.users.models.validate_tenure], verbose_name='Pass out year of the student'),
        ),
    ]
