# Generated by Django 4.0.10 on 2024-04-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('SAS', 'SAS'), ('SCORE', 'SCORE'), ('VSPARC', 'V-SPARC'), ('SMEC', 'SMEC'), ('SELECT', 'SELECT'), ('SCHEME', 'SCHEME'), ('HOT', 'HOT'), ('VITBS', 'VIT BS'), ('SCOPE', 'SCOPE'), ('VSIGN', 'VSIGN'), ('SSL', 'SSL'), ('SENSE', 'SENSE'), ('SCE', 'SCE'), ('SBST', 'SBST'), ('VAIAL', 'VAIAL')], max_length=50, null=True, verbose_name='School'),
        ),
    ]
