# Generated by Django 4.0.10 on 2023-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_userclubrelation_club_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_coordinators",
        ),
        migrations.AddField(
            model_name="event",
            name="event_coordinators",
            field=models.JSONField(default=list),
        ),
    ]
