# Generated by Django 4.0.10 on 2024-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_club_name_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('approval_pending', 'Approval Pending'), ('faculty_approved', 'Faculty Approved'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='approval_pending', max_length=50),
        ),
    ]
