# Generated by Django 4.0.10 on 2024-03-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_status'),
        ('core', '0005_spotlight'),
    ]

    operations = [
    ]
