# Generated by Django 4.0.10 on 2024-03-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0005_event_status_0005_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo link'),
        ),
    ]
