# Generated by Django 4.0.10 on 2024-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_club_logo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_coordinators',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
