# Generated by Django 4.0.10 on 2024-03-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_spotlight_hightlight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='sub_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Type'),
        ),
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('student_welfare', 'Student Welfare'), ('student_council', 'Student Council'), ('club', 'Club'), ('chapter', 'Chapter'), ('team', 'Team'), ('greviance_cell', 'Greviance Cell'), ('other', 'Other')], default='club', max_length=50, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='userclubrelation',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
