# Generated by Django 4.0.10 on 2024-03-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_faq_specialfile_alter_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
