# Generated by Django 4.0.10 on 2024-03-27 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_club_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of club/chapter')),
                ('logo_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo link')),
                ('type', models.CharField(choices=[('student_welfare', 'Student Welfare'), ('student_council', 'Student Council'), ('club', 'Club'), ('chapter', 'Chapter'), ('team', 'Team'), ('greviance_cell', 'Greviance Cell'), ('counseling_division', 'Counseling Division'), ('other', 'Other')], default='club', max_length=50, verbose_name='Type')),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Type')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='UserOrganizationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('faculty_coordinator', 'Faculty Coordinator'), ('chairperson', 'Chair Person'), ('board_member', 'Board member'), ('member', 'member')], default='member', max_length=50)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization_relations', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Organization relation',
                'verbose_name_plural': 'User Organization relations',
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.DeleteModel(
            name='UserClubRelation',
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organization'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
