# Generated by Django 4.0.10 on 2024-03-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_club_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='is_chapter',
        ),
        migrations.RemoveField(
            model_name='club',
            name='is_technical',
        ),
    ]
