# Generated by Django 4.0.10 on 2024-03-27 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_club_description'),
    ]

    operations = [
        migrations.RenameModel("Club", "Organization"),
        migrations.RenameModel("UserClubRelation", "UserOrganizationRelation"),
    ]
