# Generated by Django 4.0.10 on 2024-03-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_club_to_organization'),
    ]

    operations = [
        migrations.RenameField("UserOrganizationRelation", "club", "organization"),
        migrations.RenameField("Event", "organizing_body", "organization"),
    ]
