# Generated by Django 4.0.10 on 2024-03-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_organization_userorganizationrelation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='core_club',
        ),
    ]
