# Generated by Django 4.0.10 on 2024-03-27 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_rename_organization_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='userorganizationrelation',
            options={'verbose_name': 'User Organization relation', 'verbose_name_plural': 'User Organization relations'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organization',
            new_name='organizing_body',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_chapter',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_technical',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name of Organization'),
        ),
        migrations.AlterField(
            model_name='userorganizationrelation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization_relations', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='userorganizationrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'organizing_body')},
        ),
    ]
