# Generated by Django 4.0.10 on 2024-04-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organization',
            new_name='organizing_body',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'organizing_body')},
        ),
    ]
