# Generated by Django 4.0.10 on 2024-04-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('student_welfare', 'Student Welfare'), ('student_council', 'Student Council'), ('club', 'Club'), ('chapter', 'Chapter'), ('team', 'Team'), ('grievance_cell', 'Grievance Cell'), ('counselling_division', 'Counselling Division'), ('other', 'Other')], default='club', max_length=50, verbose_name='Type'),
        ),
    ]
